### ISSUE TITLE
Cannot read properties of undefined, reading "current"

### ISSUE THREAD

**Issue by website-sevdesk** [JustFly1984/react-google-maps-api#3040]
Hey,
we have a Bug with the package. Can you help us?
thank you very much
Best regards 
Marcel Wiskow

<img width="582" alt="Bildschirmfoto 2022-06-03 um 14 40 45" src="https://user-images.githubusercontent.com/61244436/171855717-2103831b-8032-4a35-8af0-fa524542842f.png">
<img width="626" alt="Bildschirmfoto 2022-06-03 um 14 40 58" src="https://user-images.githubusercontent.com/61244436/171855749-d2fe7b9f-9dee-4d67-ad7f-cf6d50d310f0.png">

**Comment by metal03326** [comment]
I can confirm having the same issue. 2.7.0 seems fine, but 2.8.0 onwards is broken. I'm running Preact. I've tried updating to the latest (currently 10.7.3) Preact, but issue still persist. `ReactCurrentOwner` seems undefined in `jsxDEV`

> TypeError: Cannot read properties of undefined (reading 'current')
    at jsxDEV (esm.js:969:1)
    at jsxWithValidation (esm.js:1264:1)
    at Object.jsxWithValidationDynamic [as jsx] (esm.js:1318:1)
    at ./node_modules/@react-google-maps/api/dist/esm.js (esm.js:2044:1)
    at __webpack_require__ (bootstrap:19:1)

**Comment by website-sevdesk** [comment]
Yeah  2.7.0 still works for us too...

**Comment by pavankumar-meesho** [comment]
Running 2.7.0 still facing the same issue with preact/compact. When I commented code from this library everything seems to work.

**Comment by pavankumar-meesho** [comment]
downgrading to 2.7.0 works for me. Not working with verisons above that.

**Comment by metal03326** [comment]
I just did full stack update of my app and issue still persists even with latest Preact (10.11.3). 

Interestingly, looking at [version history](https://www.npmjs.com/package/@react-google-maps/api?activeTab=versions) you can see 2.7.0 is still in top 3 of weekly downloads. Are all Preact users stuck with it?

In general 2.7.0 works fine for me, but there is this nagging `google.maps.event.addDomListener() is deprecated` that got fixed in later versions...

**Comment by kundukundu** [comment]
Any news about this issue?
