### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by irtaza9** [JustFly1984/react-google-maps-api#3096]
# I'm rendering 6k markers on the map but I got this error in the console so how can I solve this error? I want to render 1M Marker from a JSON file then how does this library behave?

# Uncaught RangeError: Maximum call stack size exceeded
    at resolveFamily (bundle.js:48516:7)
    at scheduleFibersWithFamiliesRecursively (bundle.js:46279:24)
    at scheduleFibersWithFamiliesRecursively (bundle.js:46317:11)
    at scheduleFibersWithFamiliesRecursively (bundle.js:46317:11)
    at scheduleFibersWithFamiliesRecursively (bundle.js:46317:11)
    at scheduleFibersWithFamiliesRecursively (bundle.js:46317:11)
    at scheduleFibersWithFamiliesRecursively (bundle.js:46317:11)
    at scheduleFibersWithFamiliesRecursively (bundle.js:46317:11)
    at scheduleFibersWithFamiliesRecursively (bundle.js:46317:11)
    at scheduleFibersWithFamiliesRecursively (bundle.js:46317:11)

**Comment by JustFly1984** [comment]
please provide minimal reproduction on codesandbox.io
